FROM python:3.13.0b1-slim 

RUN apt-get update && apt-get install -y curl apt-transport-https gnupg2

RUN curl -LO "https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN pip install Flask

#RUN mkdir -p /app

WORKDIR /app

COPY run.py .

ENV APP_DIRS="/Ruuter /Resql /DataMapper /Liquibase /OpenSearch /bot"
RUN mkdir -p $APP_DIRS

COPY Ruuter/private/v2/backoffice /Ruuter/private/backoffice
COPY Ruuter/public/v2/backoffice /Ruuter/public/backoffice
COPY Resql/backoffice /Resql/backoffice
COPY DataMapper/backoffice/hbs /DataMapper/backoffice/hbs
COPY Liquibase/backoffice /Liquibase/backoffice
COPY Ruuter/public/v2/Common-Services /Ruuter/public/Common-Services
COPY DataMapper/services/hbs /DataMapper/common-services/hbs

# Common Knowledge / CKB
COPY Ruuter/private/v2/ckb /Ruuter/private/ckb
COPY Ruuter/internal/ckb /Ruuter/internal/ckb
COPY Resql/ckb /Resql/ckb
COPY Resql/users /Resql/users
COPY DataMapper/ckb/hbs /DataMapper/ckb/hbs
COPY Liquibase/ckb /Liquibase/ckb

# LLM Module / RAG
COPY Ruuter/public/v2/rag-search /Ruuter/public/rag-search
COPY Ruuter/private/v2/rag-search /Ruuter/private/rag-search
COPY Resql/rag-search /Resql/rag-search
COPY DataMapper/rag-search/hbs /DataMapper/rag-search/hbs
COPY DataMapper/rag-search/lib /DataMapper/rag-search/lib
COPY Liquibase/rag-search /Liquibase/rag-search
COPY CronManager/rag-search /CronManager/rag-search

LABEL org.opencontainers.image.description Docker PRE-ALPHA image for Buerokratt-DSL

CMD ["python", "run.py"]
