getWidgetConfig:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/backoffice/get-widget-config"
  result: getWidgetConfigResult

validateWidgetConfigExists:
  switch:
    - condition: '${getWidgetConfigResult.response.body.length > 0}'
      next: mapWidgetConfigData
  next: returnNotFound

mapWidgetConfigData:
  call: http.post
  args:
    url: "[#CHATBOT_DMAPPER]/backoffice:[#CHATBOT_DMAPPER_PORT]/hbs/backoffice/return_widget_config"
    body:
      configurationArray: ${getWidgetConfigResult.response.body}
  result: widgetConfigData
  next: returnSuccess

returnSuccess:
  return: ${widgetConfigData.response.body}
  next: end

returnNotFound:
  return: "error: not found"
  next: end
