-- liquibase formatted sql
-- changeset 1AhmedYasser:1785269433
CREATE TYPE overview_date_preference_unit AS ENUM (
    'day',
    'week',
    'month',
    'period'
);

CREATE TABLE public."user_overview_date_preference" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id_code text NOT NULL,
    unit overview_date_preference_unit NOT NULL DEFAULT 'week',
    created_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT user_overview_date_preference_pkey PRIMARY KEY (id),
    CONSTRAINT user_overview_date_preference_user_id_code_key UNIQUE (user_id_code)
);
