name: Buerokratt DSL

on:
  push:
    branches:
      - dev-tmp # Adjust the branch name if needed
    # Remove paths filter to trigger on any change
    paths:
       - '.env'

jobs:
  setup_directories:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check and Create Folder Structure and copy DSLs for Ruuter v2 private
        run: |
          FOLDER_PATH=Ruuter/private/v2/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/README.yml"
          else
            echo "Folder structure already exists."
          fi

          SUBFOLDERS=("analytics" "backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH"
              touch "$SUBFOLDER_PATH/readme.yml"
              echo "Creating GET $folder ..."
              mkdir -p "$SUBFOLDER_PATH/GET"
              touch "$SUBFOLDER_PATH/GET/readme.yml"
            else
              echo "$folder folder already exists."
            fi
          done

          SOURCE_REPO_CHATBOT=buerokratt/Buerokratt-Chatbot
          SOURCE_FOLDER_CHATBOT=DSL/Ruuter.private/DSL
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_CHATBOT.git" source-repo-chatbot
          cp -R "source-repo-chatbot/$SOURCE_FOLDER_CHATBOT/." "$FOLDER_PATH/backoffice"

          SOURCE_REPO_ANALYTICS=buerokratt/Analytics-Module
          SOURCE_FOLDER_ANALYTICS=DSL/Ruuter
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_ANALYTICS.git" source-repo-analytics
          cp -R "source-repo-analytics/$SOURCE_FOLDER_ANALYTICS/." "$FOLDER_PATH/analytics"

          SOURCE_REPO_SERVICE=buerokratt/Service-Module
          SOURCE_FOLDER_SERVICE=DSL/Ruuter
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_SERVICE.git" source-repo-service
          cp -R "source-repo-service/$SOURCE_FOLDER_SERVICE/." "$FOLDER_PATH/services"

          SOURCE_REPO_TRAINING=buerokratt/Training-Module
          SOURCE_FOLDER_TRAINING=DSL/Ruuter.private
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_TRAINING.git" source-repo-training
          cp -R "source-repo-training/$SOURCE_FOLDER_TRAINING/." "$FOLDER_PATH/training"

      - name: Clean Up Cloned Repositories
        run: |
          rm -rf source-repo-chatbot
          rm -rf source-repo-analytics
          rm -rf source-repo-service
          rm -rf source-repo-training

      - name: Check and Create Folder Structure and copy DSLs for Ruuter v2 public
        run: |
          FOLDER_PATH=Ruuter/public/v2/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/readme.yml"
          else
            echo "Folder structure already exists."
          fi

          SUBFOLDERS=("analytics" "backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH"
              touch "$SUBFOLDER_PATH/readme.yml"
            else
              echo "$folder folder already exists."
            fi
          done

          SOURCE_REPO_CHATBOT=buerokratt/Buerokratt-Chatbot
          SOURCE_FOLDER_CHATBOT=DSL/Ruuter.public/DSL
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_CHATBOT.git" source-repo-chatbot
          cp -R "source-repo-chatbot/$SOURCE_FOLDER_CHATBOT/." "$FOLDER_PATH/backoffice"

          SOURCE_REPO_TRAINING=buerokratt/Training-Module
          SOURCE_FOLDER_TRAINING=DSL/Ruuter.public
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_TRAINING.git" source-repo-training
          cp -R "source-repo-training/$SOURCE_FOLDER_TRAINING/." "$FOLDER_PATH/training"

      - name: Clean Up Cloned Repositories
        run: |
          rm -rf source-repo-chatbot
          rm -rf source-repo-analytics
          rm -rf source-repo-service
          rm -rf source-repo-training

      - name: Check and Create Folder Structure and copy DSLs for RESQL
        run: |
          FOLDER_PATH=Resql/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/readme.yml"
          else
            echo "Folder structure already exists."
          fi

          SUBFOLDERS=("analytics" "backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH/GET"
              touch "$SUBFOLDER_PATH/GET/readme.yml"
            else
              echo "$folder folder already exists."
            fi
          done

          SOURCE_REPO_CHATBOT=buerokratt/Buerokratt-Chatbot
          SOURCE_FOLDER_CHATBOT=DSL/Resql
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_CHATBOT.git" source-repo-chatbot
          cp -R "source-repo-chatbot/$SOURCE_FOLDER_CHATBOT/." "$FOLDER_PATH/backoffice/POST"

          SOURCE_REPO_ANALYTICS=buerokratt/Analytics-Module
          SOURCE_FOLDER_ANALYTICS=DSL/Resql
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_ANALYTICS.git" source-repo-analytics
          cp -R "source-repo-analytics/$SOURCE_FOLDER_ANALYTICS/." "$FOLDER_PATH/analytics/POST"


          SOURCE_REPO_SERVICE=buerokratt/Service-Module
          SOURCE_FOLDER_SERVICE=DSL/Resql/training
          SOURCE_FOLDER_SERVICE_SERVICE=DSL/Resql/services
          SOURCE_FOLDER_SERVICE_USERS=DSL/Resql/users
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_TRAINING.git" source-repo-training
          cp -R "source-repo-training/$SOURCE_FOLDER_SERVICE/." "$FOLDER_PATH/training/POST"
          cp -R "source-repo-training/$SOURCE_FOLDER_SERVICE_SERVICE/." "$FOLDER_PATH/training/POST"
          cp -R "source-repo-training/$SOURCE_FOLDER_SERVICE_USERS/." "$FOLDER_PATH/training/POST"

          SOURCE_REPO_TRAINING=buerokratt/Training-Module
          SOURCE_FOLDER_TRAINING=DSL/Resql/training
          SOURCE_FOLDER_TRAINING_SERVICE=DSL/Resql/services
          SOURCE_FOLDER_TRAINING_USERS=DSL/Resql/users
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_TRAINING.git" source-repo-training
          cp -R "source-repo-training/$SOURCE_FOLDER_TRAINING/." "$FOLDER_PATH/training/POST"
          cp -R "source-repo-training/$SOURCE_FOLDER_TRAINING_SERVICE/." "$FOLDER_PATH/training/POST"
          cp -R "source-repo-training/$SOURCE_FOLDER_TRAINING_USERS/." "$FOLDER_PATH/training/POST"


      - name: Clean Up Cloned Repositories
        run: |
          rm -rf source-repo-chatbot
          rm -rf source-repo-analytics
          rm -rf source-repo-service
          rm -rf source-repo-training

      - name: Check and Create Folder Structure and copy DSLs for DATAMAPPER v1
        run: |
          FOLDER_PATH=DataMapper/v1/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/readme.yml"
          else
            echo "Folder structure already exists."
          fi

          SUBFOLDERS=("analytics" "hbs/backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH"
              touch "$SUBFOLDER_PATH/readme.yml"
            else
              echo "$folder folder already exists."
            fi
          done

          SOURCE_REPO_CHATBOT=buerokratt/Buerokratt-Chatbot
          SOURCE_FOLDER_CHATBOT=DSL/DMapper
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_CHATBOT.git" source-repo-chatbot
          cp -R "source-repo-chatbot/$SOURCE_FOLDER_CHATBOT/." "$FOLDER_PATH/hbs/backoffice/hbs"

          SOURCE_REPO_ANALYTICS=buerokratt/Analytics-Module
          SOURCE_FOLDER_ANALYTICS=DSL/DMapper
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_ANALYTICS.git" source-repo-analytics
          cp -R "source-repo-analytics/$SOURCE_FOLDER_ANALYTICS/." "$FOLDER_PATH/analytics/hbs"

          SOURCE_REPO_SERVICE=buerokratt/Service-Module
          SOURCE_FOLDER_SERVICE=DSL/DMapper
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_SERVICE.git" source-repo-service
          cp -R "source-repo-service/$SOURCE_FOLDER_SERVICE/." "$FOLDER_PATH/services/hbs"

          SOURCE_REPO_TRAINING=buerokratt/Training-Module
          SOURCE_FOLDER_TRAINING=DSL/DataMapper
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_TRAINING.git" source-repo-training
          cp -R "source-repo-training/$SOURCE_FOLDER_TRAINING/." "$FOLDER_PATH/training/hbs"

      - name: Clean Up Cloned Repositories
        run: |
          rm -rf source-repo-chatbot
          rm -rf source-repo-analytics
          rm -rf source-repo-service
          rm -rf source-repo-training

      - name: Check and Create Folder Structure and copy DSLs for Liquibase
        run: |
          FOLDER_PATH=Liquibase/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/readme.yml"
          else
            echo "Folder structure already exists."
          fi

          SUBFOLDERS=("analytics" "backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH"
              touch "$SUBFOLDER_PATH/readme.yml"
            else
              echo "$folder folder already exists."
            fi
          done

          SOURCE_REPO_CHATBOT=buerokratt/Buerokratt-Chatbot
          SOURCE_FOLDER_CHATBOT=DSL/Liquibase
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_CHATBOT.git" source-repo-chatbot
          cp -R "source-repo-chatbot/$SOURCE_FOLDER_CHATBOT/." "$FOLDER_PATH/backoffice"

          SOURCE_REPO_ANALYTICS=buerokratt/Analytics-Module
          SOURCE_FOLDER_ANALYTICS=DSL/Liquibase
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_ANALYTICS.git" source-repo-analytics
          cp -R "source-repo-analytics/$SOURCE_FOLDER_ANALYTICS/." "$FOLDER_PATH/analytics"

          SOURCE_REPO_SERVICE=buerokratt/Service-Module
          SOURCE_FOLDER_SERVICE=DSL/Liquibase
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_SERVICE.git" source-repo-service
          cp -R "source-repo-service/$SOURCE_FOLDER_SERVICE/." "$FOLDER_PATH/services"

          SOURCE_REPO_TRAINING=buerokratt/Training-Module
          SOURCE_FOLDER_TRAINING=DSL/Liquibase
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_TRAINING.git" source-repo-training
          cp -R "source-repo-training/$SOURCE_FOLDER_TRAINING/." "$FOLDER_PATH/training"

      - name: Clean Up Cloned Repositories
        run: |
          rm -rf source-repo-chatbot
          rm -rf source-repo-analytics
          rm -rf source-repo-service
          rm -rf source-repo-training

      - name: Check and Create Folder Structure and copy DSLs for OpenSearch
        run: |
          FOLDER_PATH=OpenSearch/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/readme.yml"
          else
            echo "Folder structure already exists."
          fi

          SUBFOLDERS=("services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH"
              touch "$SUBFOLDER_PATH/readme.yml"
            else
              echo "$folder folder already exists."
            fi
          done

          SOURCE_REPO_SERVICE=buerokratt/Service-Module
          SOURCE_FOLDER_SERVICE=DSL/OpenSearch
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_SERVICE.git" source-repo-service
          cp -R "source-repo-service/$SOURCE_FOLDER_SERVICE/." "$FOLDER_PATH/services"

          SOURCE_REPO_TRAINING=buerokratt/Training-Module
          SOURCE_FOLDER_TRAINING=DSL/OpenSearch
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_TRAINING.git" source-repo-training
          cp -R "source-repo-training/$SOURCE_FOLDER_TRAINING/." "$FOLDER_PATH/training"

      - name: Clean Up Cloned Repositories
        run: |
          rm -rf source-repo-service
          rm -rf source-repo-training

      - name: Check and Create Folder Structure and copy DSLs for OpenSearch 2
        run: |
          FOLDER_PATH=OpenSearch2/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/readme.yml"
          else
            echo "Folder structure already exists."
          fi

          SUBFOLDERS=("services")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH"
              touch "$SUBFOLDER_PATH/readme.yml"
            else
              echo "$folder folder already exists."
            fi
          done

          SOURCE_REPO_SERVICE=buerokratt/Service-Module
          SOURCE_FOLDER_SERVICE=DSL/Opensearch
          git clone --depth=1 --branch=dev "https://github.com/$SOURCE_REPO_SERVICE.git" source-repo-service
          cp -R "source-repo-service/$SOURCE_FOLDER_SERVICE/." "$FOLDER_PATH/services"

      - name: Clean Up Cloned Repositories
        run: |
          rm -rf source-repo-service

      - name: Commit and Push Folder Structure with Copied Contents
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A .
          git commit --amend --no-edit
          git pull origin dev-tmp --rebase
          git push
