name: Buerokratt DSL

on:
  push:
    branches:
      - v2.2-alpha-services 
    paths:
      - '.env'

jobs:
  setup_directories:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Folder Structure
        run: |
          # Function to create folder and readme
          create_folder_structure() {
            local FOLDER_PATH=$1
            shift
            local SUBFOLDERS=("$@")

            if [ ! -d "$FOLDER_PATH" ]; then
              echo "Creating base folder $FOLDER_PATH"
              mkdir -p "$FOLDER_PATH"
              touch "$FOLDER_PATH/readme.md"
            else
              echo "Base folder $FOLDER_PATH already exists."
            fi

            for folder in "${SUBFOLDERS[@]}"; do
              SUBFOLDER_PATH="$FOLDER_PATH$folder"
              if [ ! -d "$SUBFOLDER_PATH" ]; then
                echo "Creating $folder folder..."
                mkdir -p "$SUBFOLDER_PATH/GET"
                touch "$SUBFOLDER_PATH/GET/readme.md"
              else
                echo "$folder folder already exists."
              fi
            done
          }

          # Define directories and subfolders
          create_folder_structure "Ruuter/private/v2/" "analytics" "backoffice" "services" "training"
          create_folder_structure "Ruuter/public/v2/" "analytics" "backoffice" "services" "training"
          create_folder_structure "Resql/" "analytics" "backoffice" "services" "training"
          create_folder_structure "DataMapper/v1/" "analytics" "hbs/backoffice" "services" "training"
          create_folder_structure "Liquibase/" "analytics" "backoffice" "services" "training"
          create_folder_structure "OpenSearch/" "services" "training"
          create_folder_structure "OpenSearch2/" "services"

      - name: Clone and Copy DSLs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Repositories to clone
          declare -A REPOS=(
            ["buerokratt/Buerokratt-Chatbot"]="DSL/Ruuter.private/DSL Ruuter/private/v2/backoffice"
            ["buerokratt/Analytics-Module"]="DSL/Ruuter Ruuter/private/v2/analytics"
            ["buerokratt/Service-Module"]="DSL/Ruuter Ruuter/private/v2/services"
            ["buerokratt/Training-Module"]="DSL/Ruuter.private Ruuter/private/v2/training"
            ["buerokratt/Common-Services"]="DSL/Ruuter.private Ruuter/private/v2/Common-Services"
          )

          # Function to clone, copy, and clean repository data
          clone_and_copy() {
            local repo=$1
            local source_folder=$2
            local target_folder=$3
            git clone --depth=1 --branch=dev "https://github.com/$repo.git" temp-repo
            cp -R "temp-repo/$source_folder/." "$target_folder"
            rm -rf temp-repo
          }

          # Clone, copy and clean for each repository and target path
          for repo in "${!REPOS[@]}"; do
            read -r source_folder target_folder <<< "${REPOS[$repo]}"
            clone_and_copy "$repo" "$source_folder" "$target_folder"
          done

      - name: Clone and Copy DSLs for Public and Other Environments
        run: |
          # Extend REPOS array for additional environments
          declare -A REPOS_PUBLIC=(
            ["buerokratt/Buerokratt-Chatbot"]="DSL/Ruuter.public/DSL Ruuter/public/v2/backoffice"
            ["buerokratt/Training-Module"]="DSL/Ruuter.public Ruuter/public/v2/training"
            ["buerokratt/Common-Services"]="DSL/Ruuter.public Ruuter/public/v2/Common-Services"
          )

          declare -A REPOS_OTHER=(
            ["buerokratt/Buerokratt-Chatbot"]="DSL/Resql Resql/backoffice/POST"
            ["buerokratt/Analytics-Module"]="DSL/Resql Resql/analytics/POST"
            ["buerokratt/Service-Module"]="DSL/Resql/services Resql/services/POST"
            ["buerokratt/Training-Module"]="DSL/Resql/training Resql/training/POST"
            ["buerokratt/Common-Services"]="DSL/OpenSearch OpenSearch/Common-Services"
          )

          for repo in "${!REPOS_PUBLIC[@]}"; do
            read -r source_folder target_folder <<< "${REPOS_PUBLIC[$repo]}"
            clone_and_copy "$repo" "$source_folder" "$target_folder"
          done

          for repo in "${!REPOS_OTHER[@]}"; do
            read -r source_folder target_folder <<< "${REPOS_OTHER[$repo]}"
            clone_and_copy "$repo" "$source_folder" "$target_folder"
          done

      - name: Commit and Push Folder Structure with Copied Contents
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin v2.1-alpha --no-ff --allow-unrelated-histories
          git add -A .
          git commit --allow-empty -m "Update folder structure and DSL files"
          git push
