name: Buerokratt DSL - get ymls

on:
  push:
    branches:
      - v2.2-alpha-0502
    paths:
      - '.env'

jobs:
  process_dsl:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up and Process DSL Structures
        run: |
          set -e  # Exit on any error

          create_folders() {
            echo "Creating structure for $1"
            mkdir -p "$2"
            touch "$2/readme.md"
            for folder in "${3[@]}"; do
              mkdir -p "$2/$folder"
              touch "$2/$folder/readme.md"
            done
          }

          copy_and_cleanup() {
            REPO=$1
            FOLDER=$2
            TARGET=$3
            echo "Cloning and copying $REPO..."
            git clone --branch=dev "https://github.com/$REPO.git" "temp-repo"
            cp -R "temp-repo/$FOLDER/." "$TARGET"
            rm -rf temp-repo
          }

          base_dir=( "analytics" "backoffice" "services" "training" )

          # Ruuter v2 private setup
          ruuter_private_path="Ruuter/private/v2"
          create_folders "Ruuter v2 private" "$ruuter_private_path" "${base_dir[@]}"
          copy_and_cleanup "buerokratt/Buerokratt-Chatbot" "DSL/Ruuter.private/DSL" "$ruuter_private_path/backoffice"
          copy_and_cleanup "buerokratt/Analytics-Module" "DSL/Ruuter" "$ruuter_private_path/analytics"
          copy_and_cleanup "buerokratt/Service-Module" "DSL/Ruuter" "$ruuter_private_path/services"
          copy_and_cleanup "buerokratt/Training-Module" "DSL/Ruuter.private" "$ruuter_private_path/training"

          # Ruuter v2 public setup
          ruuter_public_path="Ruuter/public/v2"
          create_folders "Ruuter v2 public" "$ruuter_public_path" "${base_dir[@]}"
          copy_and_cleanup "buerokratt/Buerokratt-Chatbot" "DSL/Ruuter.public/DSL" "$ruuter_public_path/backoffice"
          copy_and_cleanup "buerokratt/Training-Module" "DSL/Ruuter.public" "$ruuter_public_path/training"
          copy_and_cleanup "buerokratt/Common-Services" "DSL/Ruuter.public" "$ruuter_public_path/Common-Services"

          # Commit changes
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit --allow-empty -m "Update DSL structures"
          git push origin v2.2-alpha-0502
