name: Buerokratt DSL - get ymls

on:
  push:
    branches:
      - v2.2-alpha-0502
    paths:
      - '.env'

jobs:
  setup_directories:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create and Populate Folder Structure for All Modules
        run: |
          # Helper function to handle common operations for multiple services
          create_and_copy_files() {
            FOLDER_PATH="$1"
            SOURCE_REPO="$2"
            SOURCE_FOLDER="$3"
            TARGET_FOLDER="$4"

            echo "Setting up folder: $FOLDER_PATH"
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/readme.md"

            if [ ! -z "$SOURCE_REPO" ]; then
              echo "Cloning $SOURCE_REPO ..."
              git clone --branch=dev "https://github.com/$SOURCE_REPO.git" temp-repo
              echo "Copying from $SOURCE_FOLDER to $TARGET_FOLDER ..."
              mkdir -p "$TARGET_FOLDER"
              cp -R "temp-repo/$SOURCE_FOLDER/." "$TARGET_FOLDER"
              rm -rf temp-repo
            else
              echo "No repository provided; skipping copy."
            fi
          }

          # Ruuter v2 private
          FOLDER_PATH=Ruuter/private/v2/
          SUBFOLDERS=("analytics" "backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            mkdir -p "$FOLDER_PATH$folder/GET"
            touch "$FOLDER_PATH$folder/GET/readme.md"
          done
          create_and_copy_files "$FOLDER_PATH/backoffice" "buerokratt/Buerokratt-Chatbot" "DSL/Ruuter.private/DSL" "$FOLDER_PATH/backoffice"
          create_and_copy_files "$FOLDER_PATH/analytics" "buerokratt/Analytics-Module" "DSL/Ruuter" "$FOLDER_PATH/analytics"

          # Resql
          FOLDER_PATH=Resql/
          SUBFOLDERS=("analytics" "backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            mkdir -p "$FOLDER_PATH$folder/GET"
            touch "$FOLDER_PATH$folder/GET/readme.md"
          done
          create_and_copy_files "$FOLDER_PATH/backoffice/POST" "buerokratt/Buerokratt-Chatbot" "DSL/Resql" "$FOLDER_PATH/backoffice/POST"

          # Datamapper
          FOLDER_PATH=DataMapper/v1/
          SUBFOLDERS=("analytics" "hbs/backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            mkdir -p "$FOLDER_PATH$folder"
            touch "$FOLDER_PATH$folder/readme.md"
          done
          create_and_copy_files "$FOLDER_PATH/hbs/backoffice/hbs" "buerokratt/Buerokratt-Chatbot" "DSL/DMapper" "$FOLDER_PATH/hbs/backoffice/hbs"

          # OpenSearch
          FOLDER_PATH=OpenSearch/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/readme.md"
          else
            echo "Folder structure already exists."
          fi
          SUBFOLDERS=("services" "training" "Common-Services")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH"
              touch "$SUBFOLDER_PATH/readme.md"
            else
              echo "$folder folder already exists."
            fi
          done
          create_and_copy_files "$FOLDER_PATH/services" "buerokratt/Service-Module" "DSL/OpenSearch" "$FOLDER_PATH/services"
          create_and_copy_files "$FOLDER_PATH/training" "buerokratt/Training-Module" "DSL/OpenSearch" "$FOLDER_PATH/training"
          create_and_copy_files "$FOLDER_PATH/Common-Services" "buerokratt/Common-Services" "DSL/OpenSearch" "$FOLDER_PATH/Common-Services"

          # OpenSearch2
          FOLDER_PATH=OpenSearch2/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/readme.md"
          else
            echo "Folder structure already exists."
          fi
          SUBFOLDERS=("services")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH"
              touch "$SUBFOLDER_PATH/readme.md"
            else
              echo "$folder folder already exists."
            fi
          done
          create_and_copy_files "$FOLDER_PATH/services" "buerokratt/Service-Module" "DSL/Opensearch" "$FOLDER_PATH/services"

      - name: Clean Up Cloned Repositories
        run: |
          rm -rf source-repo-service
          rm -rf source-repo-training
          rm -rf source-repo-Common-Services

      - name: Commit and Push Folder Structure with Copied Contents
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git reset --hard HEAD
          git pull origin v2.2-alpha-0502 --no-ff --allow-unrelated-histories
          git add -A .
          git commit --allow-empty -m "Update"
          git push
